In [12]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import FactorAnalysis
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
data=load_iris()
x=data.data
y=data.target
p=pd.DataFrame(x,columns=data.feature_names)
g=pd.DataFrame(y,columns=['target'])
print(p.shape)
p.head()

(150, 4)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
g.head()

   target
0       0
1       0
2       0
3       0
4       0

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
fa=FactorAnalysis(n_components=2)
x_fa=fa.fit_transform(x_scaled)
x_fas=pd.DataFrame(x_fa,columns=['fa1','fa2'])
print(x_fas.shape)
x_fas

(120, 2)

          fa1       fa2
0   -1.566031  0.158454
1   -1.209339 -1.958474
2    0.433659 -1.378959
3   -1.232038  0.258424
4   -1.422629  0.921218
..        ...       ...
115  0.171694 -0.353835
116  0.349631  2.816415
117 -1.363953 -2.389652
118  0.145338  0.330820
119  1.277202 -0.894890

[120 rows x 2 columns]

In [20]:
model=LogisticRegression()
model.fit(x_fas,y_train)
x_test_scaled=scaler.transform(x_test)
x_test_fa=fa.transform(x_test_scaled)
y_pred=model.predict(x_test_fa)
y_pred
y_preds=pd.DataFrame(y_pred,columns=['output'])
print(y_preds)
print(y_preds.shape)
print("accuracy_score:",accuracy_score(y_test,y_pred))

    output
0        1
1        0
2        2
3        1
4        1
5        0
6        1
7        1
8        1
9        1
10       2
11       0
12       0
13       0
14       0
15       1
16       2
17       1
18       1
19       2
20       0
21       2
22       0
23       2
24       2
25       2
26       2
27       2
28       0
29       0
(30, 1)
accuracy_score: 0.9666666666666667

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [21]:
print("Train score:",model.score(x_fas,y_train))
print("Test score:",model.score(x_test_fa,y_test))
print("accuracy_score:",accuracy_score(y_test,y_pred))
print(x_fas.shape)
print(p.shape)
print(p.head())
print(x_fas.head())

Train score: 0.975
Test score: 0.9666666666666667
accuracy_score: 0.9666666666666667
(120, 2)
(150, 4)
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
        fa1       fa2
0 -1.566031  0.158454
1 -1.209339 -1.958474
2  0.433659 -1.378959
3 -1.232038  0.258424
4 -1.422629  0.921218

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(